// <auto-generated />
using System;
using FlightBoard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBoard.Api.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20250721115237_InitialFlightSchema")]
    partial class InitialFlightSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FlightBoard.Api.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Terminal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Airline")
                        .HasDatabaseName("IX_Flights_Airline");

                    b.HasIndex("Destination")
                        .HasDatabaseName("IX_Flights_Destination");

                    b.HasIndex("FlightNumber")
                        .HasDatabaseName("IX_Flights_FlightNumber");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Flights_IsDeleted");

                    b.HasIndex("Origin")
                        .HasDatabaseName("IX_Flights_Origin");

                    b.HasIndex("ScheduledArrival")
                        .HasDatabaseName("IX_Flights_ScheduledArrival");

                    b.HasIndex("ScheduledDeparture")
                        .HasDatabaseName("IX_Flights_ScheduledDeparture");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Flights_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Flights_Type");

                    b.HasIndex("Destination", "Type")
                        .HasDatabaseName("IX_Flights_Destination_Type");

                    b.HasIndex("FlightNumber", "ScheduledDeparture")
                        .HasDatabaseName("IX_Flights_FlightNumber_ScheduledDeparture");

                    b.HasIndex("Origin", "Type")
                        .HasDatabaseName("IX_Flights_Origin_Type");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("IX_Flights_Type_Status");

                    b.ToTable("Flights", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
